server:
  port: 7010
  error:
    path: /error
    include-message: always
    whitelabel:
      enabled: false
spring:
  profiles:
    include:
      - eureka
      - pvc
      - oauth2
  application:
    name: USER-INTERFACE