server:
  port: 7010
  error:
    path: /error
    include-message: always
    whitelabel:
      enabled: false
spring:
  profiles:
    include:
      - eureka
      - pvc
  application:
    name: ${pvc.userInterface.appName}