server:
  port: 7010
  error:
    path: /error
    whitelabel:
      enabled: false
spring:
  application:
    name: USER-INTERFACE
eureka:
  instance:
    hostname: localhost:7025
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka
pvc:
  processor:
    apiPath: /api/v1