server:
  port: ${pvc.dataStorage.port}
spring:
  profiles:
    include:
      - eureka
      - pvc
      - mongodb
  application:
    name: ${pvc.dataStorage.appName}
  data:
    mongodb:
      auto-index-creation: true