spring:
  application:
    name: DATA-STORAGE
  profiles:
    include:
      - mongodb
  data:
    mongodb:
      database: PDF_to_Voice_Converter
server:
  port:
    7000
eureka:
  instance:
    hostname: localhost:7025
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka
pvc:
  file:
    localStoragePath: E:\PDF_to_Voice_Converter_storage
    localStorageSize: 2