pvc:
  dataStorage:
    apiVersion: 1
    localStoragePath: E:\PDF_to_Voice_Converter_storage
    localStorageSize: 2
  converterApi:
    apiVersion: 1
  processor:
    apiVersion: 1
  authServer:
    address: http://authserver
    port: 7020