server:
  port: 7015
spring:
  application:
    name: PROCESSOR
eureka:
  instance:
    hostname: localhost:7025
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}/eureka
pvc:
  converterApi:
    apiPath: /api/v1
  dataStorage:
    apiPath: /api/v1